FROM python:3.10-slim

WORKDIR /app

COPY requirements-fastapi.txt .
RUN pip install --no-cache-dir -r requirements-fastapi.txt

COPY ./src ./src

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]